### ISSUE TITLE
First review

### ISSUE THREAD

**Issue by memsharded** [danimtb/conan-eigen#1]
- Url field is for the URL of the package recipe. Use "homepage" for the library url
- If the license is popular, like "MIT" I would use that instead of an URL
- Why build_policy? That forces re-download at each step. Either use "missing", or I prefer to actually upload the "binary" packages to the remote repos.
- header_only() is optional in this case. Leave it, but just FYI
- Why do you need ``with tools.environment_append(RunEnvironment(self).vars):`` in test_package? This is only necessary if you aim to run binaries of your dependencies. And in that case, there might be other approaches. Also, why the LD_LIBRARY_PACKAGE here? No shared libraries here, it is header only

**Comment by danimtb** [comment]
Changes:
- Set url to repository and added homepage for website
- Set _Mozilla Public License Version 2.0_ license
- Removed `build_policy` and added no_`copy_source = True`
- Removed not needed `RunEnvironment(self).vars` from test_package

**Comment by danimtb** [comment]
Improvements:
- Created branch `<channel>/<version>` to improve CI worlflows
- Enabled Travis CI and Appveyor
- Uploaded packages to bintray [danimtb public-conan](https://bintray.com/danimtb/public-conan)
- Added image logo
- Added Bintray, Travis and Appveyor badges to readme

**Comment by danimtb** [comment]
Done!
